apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-portal.fullname" . }}-portal
  labels:
    {{- include "dev-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  type: ClusterIP
  selector:
    {{- include "dev-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
  ports:
    - name: http
      port: 8000
      targetPort: http
